name: build-docker-image

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        -   cron: '0 15 * * 3'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
            -   name: Build and push
                uses: docker/build-push-action@v3
                with:
                    platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/ppc64le,linux/s390x
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: xiaozhuai/rinetd-alpine:latest
            -   name: Checkout
                uses: actions/checkout@v3
                if: ${{ github.event_name != 'pull_request' }}
            -   name: Docker Hub Description
                uses: peter-evans/dockerhub-description@v3
                if: ${{ github.event_name != 'pull_request' }}
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
                    repository: xiaozhuai/rinetd-alpine
                    short-description: ${{ github.event.repository.description }}
